REVOKE ALL PRIVILEGES ON SCHEMA public FROM PUBLIC;

CREATE USER test_db01 WITH PASSWORD 'localdev';
GRANT CONNECT ON DATABASE test TO test_db01;
GRANT USAGE ON SCHEMA public TO test_db01;

CREATE USER test_db02 WITH PASSWORD 'localdev';
GRANT CONNECT ON DATABASE test TO test_db02;
GRANT USAGE ON SCHEMA public TO test_db02;
GRANT CREATE ON SCHEMA public TO test_db02;
